import numpy as np

# Test case 1: 2x2 system
A = np.array([[1, 2], [3, 4]])
B = np.array([[5], [6]])
C = np.array([[7, 8]])
D = np.array([[9]])
A_tilde, B_tilde, C_tilde, D_tilde = sol_diagonalize_system(A, B, C, D)
print("Test case 1:")
print("A_tilde:")
print(A_tilde)
print("B_tilde:")
print(B_tilde)
print("C_tilde:")
print(C_tilde)
print("D_tilde:")
print(D_tilde)
print()

# Test case 2: 3x3 system
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10], [11], [12]])
C = np.array([[13, 14, 15]])
D = np.array([[16]])
A_tilde, B_tilde, C_tilde, D_tilde = sol_diagonalize_system(A, B, C, D)
print("Test case 2:")
print("A_tilde:")
print(A_tilde)
print("B_tilde:")
print(B_tilde)
print("C_tilde:")
print(C_tilde)
print("D_tilde:")
print(D_tilde)
print()